# Generated by Django 6.0.2 on 2026-02-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('composite_tax_rate', models.DecimalField(decimal_places=5, default=0, help_text='Total tax rate applied to the order (state + county + city + special).', max_digits=7)),
                ('state_rate', models.DecimalField(decimal_places=5, default=0, help_text='State-level tax rate component.', max_digits=6)),
                ('county_rate', models.DecimalField(decimal_places=5, default=0, help_text='County-level tax rate component.', max_digits=6)),
                ('city_rate', models.DecimalField(decimal_places=5, default=0, help_text='City-level tax rate component.', max_digits=6)),
                ('special_rate', models.DecimalField(decimal_places=5, default=0, help_text='Special district or additional tax rate component.', max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Absolute tax amount charged for this order.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Final amount charged (subtotal + tax).', max_digits=10)),
                ('state_name', models.CharField(max_length=100)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdictions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('state', 'State'), ('county', 'County'), ('city', 'City'), ('special', 'Special')], max_length=20)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('state_code', models.CharField(blank=True, help_text="Two-letter state code, e.g. 'NY'.", max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax jurisdiction',
                'verbose_name_plural': 'Tax jurisdictions',
                'unique_together': {('type', 'name', 'state_code', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=5, help_text='Rate as fraction, e.g. 0.04000 for 4%.', max_digits=6)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.taxjurisdiction')),
            ],
            options={
                'verbose_name': 'Tax rate',
                'verbose_name_plural': 'Tax rates',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Placeholder',
        ),
    ]
