# Generated by Django 5.2.11 on 2026-02-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_rate', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CountyTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('county_rate', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('composite_tax_rate', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('state_rate', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('county_rate', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('city_rate', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('special_rates', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state_name', models.CharField(max_length=100)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_or_county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('special_rate', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='StateTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_rate', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
    ]
