# Generated by Django 5.2.11 on 2026-02-27 10:35

from django.db import migrations


def create_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")

    if not User.objects.filter(username="clodev").exists():
        User.objects.create_superuser(
            username="clodev",
            email="",
            password="clodev"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]